sudo: required
services:
  - docker

before_install:
  - docker build -t shanmicheal25/docker-react -f Dockerfile.dev .

script:
  - docker ps
  # - docker run shanmicheal25/docker-react  npm run test -- --coverage

deploy:
  provider: elasticbeanstalk ## provider about aws /azure/ any deployment 
  region: "ap-southeast-1"  
  app: "dockerImage" 
  env: "Dockerimage-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-489459884699"
  bucket_path: "e-gmnzchihdf" ## dockerImage 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
