sudo: required
services:
  - docker

before_install:
  - docker build -t shanmicheal25/docker-react -f Dockerfile.dev .


script:
  - docker run shanmicheal25/docker-react  npm run test -- --converage

